### ISSUE TITLE
Update to support 1.19.3

### ISSUE THREAD

**Issue by SlimeDog** [SlimeDog/PowerNBT#1]
Support MC 1.19.x
- [x] Update to Java 17 - don't need to support previous Java versions
- [x] Update `api-version: 1.19` - don't need to support previous MC versions
- [x] Configure dependabot
- [ ] Update dependencies
- [ ] Update NBT code as necessary
- [ ] Comment config.yml
- [ ] Implement `reload` command to reload the configuration and messages
  - [ ] Ensure that debug toggle works
- [ ] Reorganize language file en.yml
  - [ ] Organize into logical sections?
  - [ ] Sort alphabetically (within sections)
  - [ ]  Elide `locale` head tag
    - [ ] Does it serve a purpose?
    - [ ] Would require code changes

Move into SlimeDogCore universe
- [ ] Integrate with SlimeDogCore for configuration and message management, etc.
- [ ] Implement bStats (requires new SlimeDog bStats id)
- [ ] Verify `mvn clean package` compilation
- [ ] Verify usage against Spigot/Paper 1.19.3
  - [ ] /nbt inventory - show items in your inventory as nbt list
  - [ ] /nbt block - show nbt of target block
  - [ ] /nbt item - show nbt tag of item in hand

**Comment by SlimeDog** [comment]
This issue was resolved by adding the following to the `hooks:` section of `config.yml`
```
  1_19_3-R0_1-SNAPSHOT:
    entity:
      getNBTSimple: "net.minecraft.world.entity.Entity f(net.minecraft.nbt.NBTTagCompound): net.minecraft.nbt.NBTTagCompound"
      setNBT: "net.minecraft.world.entity.Entity g(net.minecraft.nbt.NBTTagCompound): void"
    block:
      getNBT: "net.minecraft.world.level.block.entity.TileEntity m(): net.minecraft.nbt.NBTTagCompound"
      setNBT: "net.minecraft.world.level.block.entity.TileEntity a(net.minecraft.nbt.NBTTagCompound): void"
```
